workflows:
  ios-build:
    name: ARKitPoseStreamer iOS Build
    environment:
      xcode: latest
    scripts:
      - name: Build archive
        script: |
          # This step builds the app and creates the .xcarchive
          # This does not require any code signing.
          xcodebuild archive \
            -scheme "ARKitPoseStreamer" \
            -archivePath "$CM_BUILD_DIR/ARKitPoseStreamer.xcarchive" \
            -destination "generic/platform=iOS"

      - name: Create unsigned .ipa
        script: |
          # This step finds the built .app file inside the archive,
          # puts it into a "Payload" folder, and zips it
          # into the final .ipa file. This .ipa is unsigned.
          
          # 1. Create the Payload directory
          mkdir -p "$CM_BUILD_DIR/build/ios/ipa/Payload"
          
          # 2. Copy the .app from the archive into the Payload dir
          cp -r "$CM_BUILD_DIR/ARKitPoseStreamer.xcarchive/Products/Applications/ARKitPoseStreamer.app" "$CM_BUILD_DIR/build/ios/ipa/Payload/"
          
          # 3. Go into the output directory
          cd "$CM_BUILD_DIR/build/ios/ipa"
          
          # 4. Zip the Payload folder into an .ipa file
          zip -r "ARKitPoseStreamer.ipa" "Payload"
            
    artifacts:
      # This tells Codemagic where to find the final .ipa file
      - build/ios/ipa/*.ipa