workflows:
  ios-build:
    name: ARKitPoseStreamer iOS Build
    environment:
      xcode: latest
    scripts:
      - name: Build archive
        script: |
          # Build the app
          xcodebuild archive \
            -scheme "ARKitPoseStreamer" \
            -archivePath "$CM_BUILD_DIR/ARKitPoseStreamer.xcarchive" \
            -destination "generic/platform=iOS"

      - name: Create valid .ipa
        script: |
          # Define paths for clarity
          IPA_DIR="$CM_BUILD_DIR/build/ios/ipa"
          PAYLOAD_DIR="$IPA_DIR/Payload"
          APP_BUNDLE="$PAYLOAD_DIR/ARKitPoseStreamer.app"
          
          # 1. Create the Payload directory structure
          mkdir -p "$PAYLOAD_DIR"
          
          # 2. Copy the built app into the Payload folder
          cp -R "$CM_BUILD_DIR/ARKitPoseStreamer.xcarchive/Products/Applications/ARKitPoseStreamer.app" "$PAYLOAD_DIR/"
          
          # 3. CRITICAL FIX: Manually overwrite the Info.plist inside the app
          # This ensures AltStore finds the valid ID and version we just created.
          cp "$CM_BUILD_DIR/Info.plist" "$APP_BUNDLE/Info.plist"
          
          # 4. Zip it all up into the .ipa file
          cd "$IPA_DIR"
          zip -r "ARKitPoseStreamer.ipa" "Payload"
            
    artifacts:
      - build/ios/ipa/*.ipa