workflows:
  ios-build:
    name: ARKitPoseStreamer iOS Build
    environment:
      xcode: latest
    scripts:
      - name: Generate Xcode project  # <-- ADD THIS SCRIPT
        script: | 
          swift package generate-xcodeproj
      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --project "ARKitPoseStreamer.xcodeproj" \
            --scheme "ARKitPoseStreamer"
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/xcarchive/*.xcarchive
