workflows:
  ios-build:
    name: ARKitPoseStreamer iOS Build
    environment:
      xcode: latest
    scripts:
      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --project "ARKitPoseStreamer.xcodeproj" \
            --scheme "ARKitPoseStreamer" \
            --destination "generic/platform=iOS"
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/xcarchive/*.xcarchive