workflows:
  ios-build:
    name: ARKitPoseStreamer iOS Build
    environment:
      xcode: latest
      vars:
        XCODE_SCHEME: "ARKitPoseStreamer"
        BUNDLE_ID: "com.mmaarrwa.ARKitPoseStreamer"
    scripts:
      - name: Clean build directory
        script: |
          rm -rf build
      - name: Build and export .ipa
        script: |
          xcodebuild -scheme "$XCODE_SCHEME" \
                     -destination 'generic/platform=iOS' \
                     -configuration Release \
                     clean archive \
                     -archivePath build/ARKitPoseStreamer.xcarchive
          xcodebuild -exportArchive \
                     -archivePath build/ARKitPoseStreamer.xcarchive \
                     -exportPath build \
                     -allowProvisioningUpdates
      - name: Verify output
        script: |
          echo "Build artifacts:"
          find build -name "*.ipa" -o -name "*.xcarchive"
    artifacts:
      - build/**/*.ipa